name: Feature Request
title: "Name your post"
description: Use this template to propose a discussion
labels: ["discussion"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to initiate this discussion!
  - type: input
    id: name
    attributes:
      label: Name
      description: So we know who you are
      placeholder: name
    validations:
      required: true
  - type: textarea
    id: discussion-body
    attributes:
      label: Feature 
      description: What would you like to see added?
      placeholder: Tell us all about it!
      value: "Tell us all about it!" 
    validations:
      required: true
  - type: textarea
    id: discussion-addition
    attributes:
      label: Context 
      description: What existing content does this feature relate to or add to?
      placeholder: Tell us how this feature enhances the current course content
    validations:
      required: true
